[package]
name = "dino"
version = "0.1.0"
authors = ["Sunjay Varma <varma.sunjay@gmail.com>"]
description = "Compiler for the dino programming language"
edition = "2018"

[dependencies]

[dev-dependencies]
rayon = "1.3"
tempfile = "3.1"

[build-dependencies]
build-helper = "0.1"
