[package]
name = "dino"
version = "0.1.0"
authors = ["Sunjay Varma <varma.sunjay@gmail.com>"]
description = "Compiler for the dino programming language"
edition = "2018"

[dependencies]
salsa = "0.14"

[dev-dependencies]
rayon = "1.3"
tempfile = "3.1"
