[package]
name = "disco"
version = "0.1.0"
authors = ["Sunjay Varma <varma.sunjay@gmail.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tempfile = "3.1"
lalrpop-util = "0.17"
regex = "1.3"

[build-dependencies]
lalrpop = "0.17"
